--------------------------------------------------------
--  File created - Thursday-August-11-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PENGGUNA
--------------------------------------------------------

  CREATE TABLE "PELATIHAN"."PENGGUNA" 
   (	"ID" NUMBER, 
	"USERNAME" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 0, 
	"ID_JABATAN" NUMBER, 
	"ID_UNIT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PENGGUNA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PELATIHAN"."PENGGUNA_PK" ON "PELATIHAN"."PENGGUNA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PENGGUNA_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PELATIHAN"."PENGGUNA_UK" ON "PELATIHAN"."PENGGUNA" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger TRG_PENGGUNA
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PELATIHAN"."TRG_PENGGUNA" 
    BEFORE INSERT ON PENGGUNA 
    FOR EACH ROW
BEGIN
  if inserting then 
      if :NEW."ID" is null then 
         select SEQ_PENGGUNA.nextval into :NEW."ID" from dual; 
      end if; 
   end if; 
END;
/
ALTER TRIGGER "PELATIHAN"."TRG_PENGGUNA" ENABLE;
--------------------------------------------------------
--  Constraints for Table PENGGUNA
--------------------------------------------------------

  ALTER TABLE "PELATIHAN"."PENGGUNA" ADD CONSTRAINT "PENGGUNA_UK" UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PELATIHAN"."PENGGUNA" ADD CONSTRAINT "PENGGUNA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PENGGUNA
--------------------------------------------------------

  ALTER TABLE "PELATIHAN"."PENGGUNA" ADD CONSTRAINT "PENGGUNA_FK1" FOREIGN KEY ("ID_JABATAN")
	  REFERENCES "PELATIHAN"."JABATAN" ("ID") ENABLE;
  ALTER TABLE "PELATIHAN"."PENGGUNA" ADD CONSTRAINT "PENGGUNA_FK2" FOREIGN KEY ("ID_UNIT")
	  REFERENCES "PELATIHAN"."MASTER_UNIT" ("ID") ENABLE;
